// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Billing struct {
	ID               uuid.UUID    `json:"id"`
	BillNumber       string       `json:"bill_number"`
	Name             string       `json:"name"`
	BaseAmount       int64        `json:"base_amount"`
	FineAmount       int64        `json:"fine_amount"`
	TotalAmount      int64        `json:"total_amount"`
	CreatedAt        time.Time    `json:"createdAt"`
	PayTimestampt    sql.NullTime `json:"pay_timestampt"`
	RefferenceNumber string       `json:"refference_number"`
	IsPayed          sql.NullBool `json:"isPayed"`
}
