// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
)

type Querier interface {
	CheckBill(ctx context.Context, arg CheckBillParams) (Billing, error)
	CreateBilling(ctx context.Context, arg CreateBillingParams) (Billing, error)
	GetBillingByNumber(ctx context.Context, billNumber string) (Billing, error)
	PayBill(ctx context.Context, arg PayBillParams) (Billing, error)
}

var _ Querier = (*Queries)(nil)
